entity_role_view_mode_switcher.rule.*:
  type: config_entity
  label: 'View Mode Switcher Rule config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    conditions:
      type: sequence
      label: 'Conditions'
      sequence:
        type: mapping
        label: 'A rule condition'
        mapping:
          negate:
            type: boolean
            label: 'Negate the condition'
          role_id:
            type: string
            label: 'The role this rules''s condition applies to.'
          original_view_mode_id:
            type: string
            label: 'The original view mode this rules''s condition applies to.'
          new_view_mode_id:
            type: string
            label: 'The new view mode this rules''s condition applies to.'
